### ISSUE TITLE
master does not compile because of -Werror on newest gcc-7.2.1

### ISSUE THREAD

**Issue by Warchant** [rttrorg/rttr#104]
Here is one of problems:

```bash
rttr/detail/method/method_wrapper.h:213:7: error: mangled name for ‘virtual rttr::detail::method_wrapper<bool (std::__cxx11::basic_string<char>::*)() const noexcept, (rttr::access_levels)0, rttr::detail::default_invoke, rttr::detail::default_args<>, rttr::detail::parameter_infos<>, 0>::~method_wrapper()’ will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
```

OS: Arch Linux
Compiler: gcc-7.2.1
-std=c++14

There are possible solutions:
https://stackoverflow.com/questions/46798456/handling-gccs-noexcept-type-warning
Personally I like just disabling this type of warnings: `-Wno-noexcept-type`

This problem happened on the computer of one of our coworkers, so I can not provide full list of errors, because I can not reproduce it personally.

**Comment by gabyx** [comment]
see PR #100

**Comment by acki-m** [comment]
Fixed and changes are in in current master branch
