### ISSUE TITLE
rttr::variant why only const getter?

### ISSUE THREAD

**Issue by gabyx** [rttrorg/rttr#108]
why can we not get the object as non-const reference?

```cpp
rttr::variant instance = rttr::type::get_by_name("MyMessage").create();
const MyMessage& r = instance.get_value<MyMessage>();
```
I could use the policy as `rttr::policy::ctor::as_std_shared_ptr` or `rttr::policy::ctor::as_raw_ptr`.
then get the pointer (`MyMessage* & const`) . Is there a reason, why it returns a `const T&`?

Would it be possibe to have a policy which constructs a `std::unique_ptr`? Probably its not so easy as `std::move` is needed internally when we get the object. 

```
std::unique_ptr r =  instance.get_value<MyMessage>();
```
-> SFINAE which enables a `get_value` function which `std::move`s the stuff out?

Background:
I try to use this rttr stuff for serializing/deserializing messages, (serialize the type, here the `MyMessage` string, and the payload)

**Comment by acki-m** [comment]
Regarding `unique_ptr` take a look at #10 
But I am open for other workarounds.
Regarding the non-const-getter. I think I can add one.
For the moment I don't see a problem. Don't know what the original reason was anymore.

Mhm... mabye I can add a support for moving values out. However, the `variant` class will always store only copy constructible values.
