### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by publicocean0** [rttrorg/rttr#109]
hi your library is fantastic! but it seams is not possible actually to add a block code dinamically: if for example i create dinamically a class containing function x() how to write dinamically the code inside? 
In the page http://www.rttr.org/doc/master/register_classes_page.html I would image 
the feature : method("print_value", "std::cout << m_value; ");

**Comment by acki-m** [comment]
You can already register lambdas:
```
rttr::register::method("print_value", [](int value){ std::cout << m_value; });
```
Do you want this?

**Comment by publicocean0** [comment]
it could be.Sorry i m not so expert like you in c++. A lambda function in assembly is equal to class function or a static function or it depends by compiler? Just for understanding what performance i m writing using lambda operator.

**Comment by publicocean0** [comment]
I gave a look to https://stackoverflow.com/questions/41453/how-can-i-add-reflection-to-a-c-application, if i understand correctly the performance are similar , it add just static information about class inside. It look like what java does

**Comment by acki-m** [comment]
RTTR uses standard C++ mechanism to reflect the class items. Pointer of members or properties will be stored and later invoked.
Is your question solved? Then you can close it.

**Comment by publicocean0** [comment]
yes, I think your libray is already the best so :)
