### ISSUE TITLE
Registration of pointer types

### ISSUE THREAD

**Issue by taketwo** [rttrorg/rttr#11]
Hi, I'm migrating my project from `0.9.0` to the current `master` and can't figure out what is the "right" way to register a pointer type for a class.

Suppose I have class `MyClass`. In old times, in the header file I would write:

```cpp
RTTR_DECLARE_STANDARD_TYPE_VARIANTS(MyClass)
```

and then in the implementation file:

```cpp
RTTR_DEFINE_TYPE(MyClass*)
RTTR_REGISTER
{
  rttr::class_<MyClass>();
}
```

This makes sure that both the class and the pointer-to-class are known by RTTR. With the new version, however, we only need:

```cpp
RTTR_REGISTRATION
{
  rttr::registration::class_<MyClass>("MyClass");
}
```

However, this way `MyClass*` is not visible to RTTR.

I found `RTTR_REGISTRATION_STANDARD_TYPE_VARIANTS` macro which seems to do what I need, however it's in `detail` and is not mentioned in the tutorial or docs (at least I did not see it). So I wonder if this is the "official" way to register pointer types. If not, then what should I use?

Thanks.

**Comment by acki-m** [comment]
The new mechanism works implicit. When you need a type object you can now directly write:
```
auto t = type::get<MyClass*>();
```
This will implicit register the type when its not yet registered.

At this point you can now use type::get_by_name("MyClass*"); 
See: http://www.rttr.org/doc/master/rttr_type_get_page.html

That means you could write something like this:
```
RTTR_REGISTRATION
{
  rttr::registration::class_<MyClass>("MyClass");
  rttr::type::get<MyClass*>();
}
```
I could add this implicit registration of pointer types during the registration of a class. Don't know if this is necessary, other people may not need it.

The official way is to just retrieve the type object on demand when you need it.

Hopes this helps.

Btw.: In which situation did you noticed the type was not registered?

**Comment by taketwo** [comment]
Thanks for the prompt response. This explicit registration through `rttr::type::get` is exactly how I am going around the problem at the moment, but it does not look nice and intuitive. I'm not against explicit registration of pointer types per se. (As you mentioned, others may not need them.) But I don't like that we achieve it as a side effect of `get`.

My use case is following. Suppose I have a hierarchy of classes (let's say `Widget`s) and store pointers to base class in a vector, i.e. `std::vector<Widget*>`. I want to recursively introspect this vector and its contents, e.g. print all properties of all contained objects. This requires down-casting pointers to their "real" class. To achieve this, implemented the following algorithm:

0. Input: object inside `rttr::variant` with type being the pointer to base class `Widget*`
1. Get all derived classes of this type. This returns (non-pointer) types `WidgetA`, `WidgetB`, etc.
2. For each type T registered with RTTR
  * check if the the object can be converted to T
  * check if raw type of T is among derived classes
  * if both conditions are true, convert and recurse

It's quite awkward and, apparently, relies on that pointers are registered with RTTR. Perhaps RTTR can provide some facility to do down-casting out-of-the-box?

**Comment by acki-m** [comment]
Do you work directly with `std::vector<Widget*>` or do you have a `std::vector<variant>`?
When you have the pointer types, you can just use following:
```
std::vector<Widget*> vec;
for (const auto& w : vec)
   type derived_type = type::get(*w);  // remark the dereferencing of the pointer
```
This works similar to typeid:
https://en.wikipedia.org/wiki/Run-time_type_information#Example
See for reference:
http://www.rttr.org/doc/master/rttr_type_get_page.html
Tutorial:
http://www.rttr.org/doc/master/five_minute_tutorial_page.html


however when you work with variant, you have to use the new (in 0.9.6)
[rttr::instance::get_derived_type ()] (http://www.rttr.org/doc/master/classrttr_1_1instance.html#add64f554ada81185dfe63ed6c0c2e666)
```
std::shared_ptr<BaseWidget> widget = std::make_shared<DerivedWidget>();
variant var = widget ;
instance obj = var;
type derived_type = obj.get_derived_type();
```
I hope this clarifies everything. 

PS:
You are aware that invoke of the properties can just be done with the variant object or the base class instance pointer, although you have derived properties?

**Comment by taketwo** [comment]
I work with `std::vector<variant>`. Actually, I am implementing a GUI widget which tries to display all properties of an object recursively. Some of my objects have array properties with polymorphic objects, hence this problem. I really need to go down the class hierarchy recursively, so if I understand correctly, you suggestion from "PS" is not relevant.

But, your second suggestion looks like what I need! I'll give it a try and report results.

**Comment by taketwo** [comment]
Your second snippet together with the "PS" hint solved my issue! After obtaining `derived_type` I can iterate over its properties and query their values directly from the `obj` instance without the need convert it to the derived class, just like you said.

So, as it often happens, I was trying to solve the [XY Problem](http://xyproblem.info/). Thanks a lot for the help and the library!
