### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by weatherhead99** [rttrorg/rttr#111]
Hi,
first of all thanks so much for all the work on rttr, it is invaluable to me!

I am wondering, is there going to be another "release" at some stage? There are a lot of improvements in the code base since 0.9.5, but for various reasons there are projects where I can't use a dependency without a "named" version - if not a release, perhaps just some tagged commit / branch more recent than the 0.9.5 version?

Thanks!

**Comment by acki-m** [comment]
I am going to release a new official version this month.

PS: I saw that you are working on in conan-rttr package. How does RTTR with conan work? I would like to have support for conan.

**Comment by weatherhead99** [comment]
There is a package for 0.9.5 that works on linux under GCC, and will soon work on windows as well. 
It is usable with no changes to the buildsystem of the downstream project (i.e. using find_package() in cmake still works). 

I am thinking that one reason I want a newer release is so I can package it, since the buildsystem has become much nicer especially for macOS and clang in general.

I am very happy to patch up the conan recipe for in source building and contribute it via a PR if you are interested in this. This is in general the conan devs' "ideal preferred" solution for a conan package. Then we could probably get rttr into the official repository at some point (rather than just my own bintray)

**Comment by acki-m** [comment]
So when I make a new release, you can make the PR and add conan support, not before?
Where would be the precompiled binaries stored?

**Comment by weatherhead99** [comment]
The way the package recipe would look has changed since 0.9.5, but I will
start working on one for the current code base. The PR can be any time,
when I get to work on it. I will try and work on  it soon, since you are
amenable.
The binaries initially would be on whatever conan repo you like - at the
moment they are on my conan repo (
https://bintray.com/weatherhead99/conan_packages) but they can be on any
remote you like.

If we got the packages accepted by the conan team, they would end up in
conan-center (https://bintray.com/conan/conan-center) - everyone gets this
repo by default when they install conan.

**Comment by acki-m** [comment]
When you make a PR, what would this contain, would this be some single new file?
I saw for poco, they made a new repo for it: https://github.com/pocoproject/conan-poco
Don't know what the reason for this it. Anyway, I am happy about your collaboration.

**Comment by weatherhead99** [comment]
most upstream packages don't care about conan, so the usual procedure is to
have separate repo for the package. The PR would contain a couple of files:
conanfile.py (recipe), test_package/conanfile.py (package test),  also CI
config for the packages if you want.

**Comment by acki-m** [comment]
@weatherhead99 
Here you go: https://github.com/rttrorg/conan-rttr
A fresh repository for you

**Comment by acki-m** [comment]
@weatherhead99 
What is the current state? Do you need help somewhere?

**Comment by weatherhead99** [comment]
hey sorry for my slowness, stuff in real life came up. I will do a PR tomorrow, promise :-)

**Comment by acki-m** [comment]
yeah, keep it coming 👍

**Comment by weatherhead99** [comment]
I have started on importing my previous package and converting it to an in source build. Work so far is here: https://github.com/weatherhead99/rttr/tree/conan

it's not quite ready yet as needs some more changes from the 0.9.5 version I previously had. Nearly there...

**Comment by ZaMaZaN4iK** [comment]
What is the status of the packaging? Can you poush your Conan package to conan-center?

**Comment by acki-m** [comment]
Who has to push what to conand-center?

**Comment by ZaMaZaN4iK** [comment]
@acki-m Someone who is responsible for this package.

**Comment by acki-m** [comment]
@weatherhead99 
Done. Tag is set. Here is the link to the archive: https://github.com/rttrorg/rttr/archive/v0.9.6.tar.gz
Can you push your PR to this repo here: https://github.com/rttrorg/conan-rttr

**Comment by acki-m** [comment]
What is the current state here with conan.

@ZaMaZaN4iK 
What is a conan package? I don't know what to submit. Maybe @weatherhead99  can say something to this?
