### ISSUE TITLE
MSVC 2017 Compile Issues rttr_core

### ISSUE THREAD

**Issue by kannode** [rttrorg/rttr#118]
When compiling main.cpp  there is the following error and can be fixed by adding to the CMakeLists File.
if(MSVC)
	add_definitions("-D_SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING")
endif()

1>------ Build started: Project: unit_tests, Configuration: Release x64 ------
1>pch.cpp
1>main.cpp
1>D:\nodein\nusr\rttr\3rd_party\catch-1.8.2\catch/catch.hpp(8527): error C2220: warning treated as error - no 'object' file generated
1>D:\nodein\nusr\rttr\3rd_party\catch-1.8.2\catch/catch.hpp(8527): warning C4996: 'std::uncaught_exception': warning STL4006: std::uncaught_exception() is deprecated in C++17. It is superseded by std::uncaught_exceptions(), plural. You can define _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include\exception(17): note: see declaration of 'std::uncaught_exception'

**Comment by acki-m** [comment]
On my tests it looks good:
https://ci.appveyor.com/project/acki-m/rttr/build/job/708vrlbbf6umts5i
Do you use the latest update of MSVC2017?
Anyway, I think I have to update catch before the 0.9.6 release
