### ISSUE TITLE
0.9.6 ???

### ISSUE THREAD

**Issue by NuckNuck** [rttrorg/rttr#146]
Hi,

I'm a little bit confused about the current version. RTTR uses a three digit versioning scheme. These suggests that

0 => is the **api** version
9 => is the **feature** version
6 => is the **bugfix** version

In the current release are some big binary and source incompatible api changes. So it is not possible to use 0.9.5 AND 0.9.6 on the same server. I'm following your commit messages over some weeks and my expectation was  version 1.0.0.

It's better to increase the last number for every bugfix, the middle number for new **binary/source compatible**  features and the first number for **binary/source incompatible** api changes.

This is a standard versioning scheme. The major version should also be a part of the library filename (librttr0.so or librttr1.so)

Don't misunderstand me. You library a really nice piece of software but the versioning scheme... :-o

Bastian

**Comment by acki-m** [comment]
yeah, your right. But I need still some feature for a 1.0.0 release.
So the other way would be to increase to 0.10.0, but this looked even worse for me. Far away from a 1.0.0 release.
However, I think I will release a 1.0.0 pretty soon.

What about the version number in the library name, is it not included? Btw. `library0.lib`  look pretty strange to me...

**Comment by NuckNuck** [comment]
Don't try to be perfect.
The version 1.0.0 is something special but nothing magically ;-)

The version in the library filename is missing. cmake generates a library named
**librttr_core.so**

Under Unix/Linux it is a "best practice" to generate the versions into the filename. This is an example
./libwo-ecs-qt.so -> ./libwo-ecs-qt.so.0
./libwo-ecs-qt.so.0 -> ./libwo-ecs-qt.so.0.1.0
./libwo-ecs-qt.so.0.1.0

In my CMakeLists.txt  are these lines:
project(wo-ecs-qt VERSION 0.1.0 DESCRIPTION ":-)")
set_target_properties(wo-ecs-qt PROPERTIES VERSION ${PROJECT_VERSION})
set_target_properties(wo-ecs-qt PROPERTIES SOVERSION ${PROJECT_VERSION_MAJOR})

With 0.9.6 I start to wrap your library and generate my own versions. I want to install and use RTTR in version 0 und version 1 on the same machine.

I'm excited to see your project growing.
Greetings Bastian

**Comment by acki-m** [comment]
@NuckNuck 
as far as I can see there the version tag is set in the property settings:
https://github.com/rttrorg/rttr/blob/master/src/rttr/CMakeLists.txt#L52
Or does it not work?
