### ISSUE TITLE
Consider removing "PERMISSIONS OWNER_READ" in CMake install commands

### ISSUE THREAD

**Issue by Ghabry** [rttrorg/rttr#147]
The *.cmake files in the CMake/ folder use "PERMISSIONS OWNER READ" for the install command.
This is problematic because when you do e.g. "sudo make install" to "/usr/local" the files will be only "rw-------" and not usable by a normal user.

Is there any reason for these permissions? If not I would suggest removing this option to get "rw-r--r--" (or whatever the umask is configured to).

**Comment by acki-m** [comment]
Yes, there is a reason for this. I wanted to avoid accidental changes of the header files.
It sometimes happens for me that I accidental change a header an save this changes.
However, does it help you when we change it to read for all roles?
Can you do a PR? just search for `install` and replace the permission to the correct one.

**Comment by Ghabry** [comment]
Read for all is fine, doing a PR later, thanks!

**Comment by acki-m** [comment]
@Ghabry 
Do you want to make a PR?

**Comment by soroshsabz** [comment]
@acki-m I create a PR for this, please review it.

thanks
