### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by kravlost** [rttrorg/rttr#148]
The link to Nonius here: http://www.rttr.org/doc/master/building_install_page.html links to http://flamingdangerzone.com/nonius/ whereas Nonius is on https://nonius.io

The name "flamingdangerzone" doesn't inspire confidence! ;-)

**Comment by acki-m** [comment]
any PR, is welcome to fix it.
Btw. Nonius seems to be not maintained anymore. When you like, you can replace it with google benchmark.

**Comment by slurps-mad-rips** [comment]
@acki-m (If it helps, nonius was integrated into Catch2 very recently!)
