### ISSUE TITLE
Compilation error with derived class

### ISSUE THREAD

**Issue by steronydh** [rttrorg/rttr#149]
version 0.9.5-2 in vcpkg; VS2017

If I use derived structs:
```
    struct Base { public: RTTR_ENABLE() };
    struct Derived : Base { public: RTTR_ENABLE(Base) };

    Derived d;

    std::vector<type> base_list = type::get(d).get_base_classes();

    for (auto& t : base_list)
        std::cout << t.get_name() << std::endl; // 'struct Base'

```

it compiles; with derived classes (just changing `struct` to `class`) I get an error:

`c:\users\public\documents\vcpkg\installed\x86-windows\include\rttr\detail\type\base_classes.h(100): error C2243: 'static_cast': conversion from 'main::Derived *' to 'main::Base *' exists, but is inaccessible`

**Comment by steronydh** [comment]
My bad: the derived class needs to be derived as `public`. *facepalm*

**Comment by acki-m** [comment]
You use, 0.9.5, why not the latest release 0.9.6?
