### ISSUE TITLE
0.9.6 in Windows7SP1 , the Example can not enter the 'Main' entry

### ISSUE THREAD

**Issue by koxter** [rttrorg/rttr#151]
I created my own instance project but the same problem exists.
But in win10 these examples work well.

**Comment by acki-m** [comment]
Your instance project? What are you talking about?
I need more info here (compiler, testcase code, etc...), otherwise I close it.

**Comment by acki-m** [comment]
Do you have to use VS2013?
When I use VS 2017 builds, they are working without a problem in Win7
I have at the moment no MSVC setup to debug this issue on Win7.

However, you are free to do.

**Comment by acki-m** [comment]
I checked it now on a Win7 system and the error is happening here:
https://github.com/rttrorg/rttr/blob/249d2d4ae95488e5452ba8203641a166196c64c6/src/rttr/detail/type/type_register.cpp#L484

So I guess it's a MSVC2013 bug, maybe you cannot use locks before entering main....I don't know.
I guess I cannot do anything about it, only I#ifdef` the `std::mutex` for this compiler. 
However, I will drop MSVC2013 support anyway.
