### ISSUE TITLE
compiler independent rtti::type serialization and templates

### ISSUE THREAD

**Issue by gabyx** [rttrorg/rttr#155]
For a file format I need to serialize the type.
This, I so far do by `rttr::type::get_name()` since its consistent over process runs (unlike `rttr::type::get_id()`)
The name is compiler dependent, that means my file format is not compatible with builds with different compilers. So far for users of my library which simple non-template classes there is a way of giving the  class a unique name, by `RTTI_REGISTRATION` in the `.cpp` file
```
RTTI_REGISTRATION
{
rttr::registration::class_<Derived>("Derived")
}
```
However, if the user writes a template class `template<typename T> class Derived`, there is no source file.
Is there any feasible procedure, to make the user define (or procedural compute) a unique name for all instantiation which happen for the template (such that all instantiated types have a `RTTI_REGISTRATION` )?

For templates I so far rely on the compiler dependent `get_name` (which you extract with the  `__PRETTY_FUNCTION__` macro and similar (?)).

Hm, strange problem ...

**Comment by acki-m** [comment]
@gabyx 
You can only registered instantiated types( e.g. `std::vector<int>`). I cannot think of any way to register a template and automatically register all instantiated types.
However, what you always can do is, you can write yourself a function template, which all allows you to easily register new template instances:

```
template<typename T>
void register_derived(std::string name)
{
    rttr::registration::class_<Derived<T>>(name)
                              .constructor<>();
    //....
}
```

Does this answer your question?

**Comment by acki-m** [comment]
Can I close this?
