### ISSUE TITLE
Hot reloading and standard types issues

### ISSUE THREAD

**Issue by mrtrizer** [rttrorg/rttr#158]
Hi! I'm trying to use hot reloading feature in my project. But when number of translation units of a library is changed, hot reloading leads to a stable reproducible crash somewhere in registration of std::string type (standard_types.cpp : line 72)

I guess that the problem is usage of RTTR_REGISTRATION instead of RTTR_PLUGIN_REGISTRATION. 

But may be I'm wrong and I'm trying to find a problem in a wrong place. Any ideas?

**Comment by mrtrizer** [comment]
Tried to remove registration of standard types from host application and replace `RTTR_REGISTRATION` with `RTTR_PLUGIN_REGISTRATION` in the library. 
But loading files anyway, on this step this time: `RTTR_REGISTRATION_STANDARD_TYPE_VARIANTS(signed char)`. Seems, the problem is deeper.

**Comment by acki-m** [comment]
I have a unit tests, which loads-unloads-loads-unloads a plugin. So somehow comparable to hot reloading. I got no crash at all.

You said it crashes in `standard_types.cpp`. This is a file from `rttr_core.dll`, You should not reload this dll. And I cannot imagine how this dll is reloaded.

However, without any simple test case, I cannot do anything.

**Comment by mrtrizer** [comment]
Okay, thank you. I'm building sources with the own build system. And `standard_types.cpp` is built within the static library. Then I'm linking this static library to both plugin and host application. Seems, this is not the right thing :) Will try to work out this issue.

**Comment by mrtrizer** [comment]
Thank you for the clue! Using of dynamic library with static linking solved my problem. I know, this looks obvious, but I've added few words about this to the plugin documentation. Also added a reference to the example.
