### ISSUE TITLE
Using copy constructor with user defined classes.

### ISSUE THREAD

**Issue by NikolaMr** [rttrorg/rttr#160]
Hi, I have been using rttr library for a few months now and I have to say that you've managed to do quite an outstanding job with it. Congratulations!

I have an issue with the user-defined copy constructor. I get feedback that it is a valid constructor but when I invoke it the output it gives me is an invalid variant. Here is a minimalistic example of the problem at hand, I would be very thankful if you could address this issue. 

```
#include <rttr\registration.h>
#include <rttr\rttr_enable.h>
#include <rttr/registration_friend>

class A
{
public:
	int a;
	A() {}
	A(const A& other) : a(a) {}
	A& operator=(const A& other) { a = other.a; }
	RTTR_ENABLE()
		RTTR_REGISTRATION_FRIEND
};

class B : public A
{
public:
	int b;
	B() {}
	B(const B& other) : A(other), b(other.b) {}
	B& operator=(const B& other) { a = other.a; b = other.b; }
	RTTR_ENABLE()
		RTTR_REGISTRATION_FRIEND
};

RTTR_REGISTRATION
{
	rttr::registration::class_<B>("B")
	.constructor<>() (rttr::policy::ctor::as_raw_ptr)
	.constructor<const B&>() (rttr::policy::ctor::as_raw_ptr);

	rttr::registration::class_<A>("A")
	.constructor<>() (rttr::policy::ctor::as_raw_ptr)
	.constructor<const A&>() (rttr::policy::ctor::as_raw_ptr);
}

void main()
{
	A* b = new B();
	A* a = new A();

	rttr::instance instance = b;
	rttr::type instanceType = instance.get_derived_type();
	rttr::constructor ctorRenCopy = instanceType.get_constructor({ instanceType });
	bool isCtorValid = ctorRenCopy.is_valid();
	rttr::variant var = ctorRenCopy.invoke(instanceType);
	bool isVarValid = var.is_valid();
	
	B* pb = var.get_wrapped_value<B*>();
}
```

Thanks and keep up the good work.
Best regards,
Nikola

**Comment by acki-m** [comment]
You want to retrieve the constructor which has an argument of `rttr::type`
```
rttr::variant var = ctorRenCopy.invoke(instanceType);
```
You provide the wrong argument type.

You should instead do  following:
```
rttr::variant var = ctorRenCopy.invoke(type::get<B>());
```
When this fixes your issues, feel free to close it.

PS: never include a `.h` file from RTTR, always include one of these:
#include <rttr/registration>
#include <rttr/registration_friend>
#include <rttr/type>

**Comment by NikolaMr** [comment]
Thanks for the response! @acki-m 

I have tried the approach that you have suggested but it isn't working, it gives the same output as the approach I've used. 
By the way, isn't it that the approach that you're suggesting doesn't give access to the variable that the copy needs to be made from since this approach invokes the copy constructor on some type that isn't bound to some specific object instance? 

Thanks for the advice about header inclusions. I will fix it.

Best regards,
Nikola

**Comment by acki-m** [comment]
@NikolaMr 
Ahh sorry my fault, you have to provide a valid instance of type `B`
So this should work:
```
A* b = new B();
rttr::variant var = ctorRenCopy.invoke(*b);
```

**Comment by NikolaMr** [comment]
@acki-m 
Thanks for the reply.
This doesn't work either. But this works:
```
A* b = new B();
rttr::variant var = ctorRenCopy.invoke(*((B*)b));
```
But the problem is that I want to be able to call copy constructor without knowing what is the actual class of the object so this isn't the solution to the problem I'm having.
From what I see in the documentation, the problem is that the constructor's invoke method expects **exactly** the same type of parameters. Is there a way to cast the argument to the constructor's invoke method to the underlying type (using the one obtained by rttr::type instanceType = instance.get_derived_type())?

**Comment by acki-m** [comment]
@NikolaMr 
Arguments to function calls will never be converted automatically. So you have to do this yourself.
However, when you store data inside a variant it has to be always copied. That means you cannot work with references. Otherwise it will be copied. I have unfortunately no solution for this problem.

Does this help you some how? Can you work around it?

**Comment by NikolaMr** [comment]
In the end, I have solved the issue by manually converting the arguments since I haven't found a RTTR friendly workaround.
