### ISSUE TITLE
get_derived_classes() may return incorrect data when working with dynamic plugins

### ISSUE THREAD

**Issue by bsviglo** [rttrorg/rttr#163]
I have specific use case where I have a base class BaseClass which is registered in rttr in the main application. There are several derived from it classes which are also registered in rttr.
I also have a plugin which registers number of classes which are all derived from the BaseClass.
Main application dynamically loads plugin.
That all works ok until I start hot reloading. Hot reloading works, but it seems that `rttr::type<BaseClass>::get_derived_classes() `returns invalid types or crashes because of the access violation.

Seems that `class_data::m_derived_types` (of `rttr::type<BaseClass>`) is not properly cleaned after unloading plugin.

**Comment by acki-m** [comment]
This is indeed a bug.
