### ISSUE TITLE
how to set value for a wrapper variant

### ISSUE THREAD

**Issue by rovingstar** [rttrorg/rttr#167]
Hello,

is there a way to set wrapped_value of an variant (if it is a wrapped type)
just like the opposite of rttr::variant::extract_wrapped_value()

Thanks.

**Comment by acki-m** [comment]
I don't get it really, what are you trying to achieve?

you mean you have something like this:
```
int value = 12;
int value2 = 42;
variant var = std::ref(value);
var = value2;
// var contains now a std:ref with value2?
```
Something like this?

**Comment by rovingstar** [comment]
Hi,

I want to set var to value2 (copy, still ref to value), but only through variant operation...

**Comment by acki-m** [comment]
```
int value_1 = 2;
variant var = std::ref(value_1);
auto& value_2 = var.get_wrapped_value<int>(); // will return a const&
```
[variant::get_wrapped_value](http://www.rttr.org/doc/master/classrttr_1_1variant.html#afe2a41d4f56e403dd97f0057b6925e07)

**Comment by rovingstar** [comment]
Hi,

do you mean I use value_2 as an non-const & ?
like this:

```
int value_1 = 2;
variant var = std::ref(value_1);
auto& value_2 = var.get_wrapped_value<int>(); // will return a const&
value_2 = value_1;  //compile error
(int&)value2 = value_1; //ok

```

if so,  why variant::get_wrapped_value() returns const& insetead of & ?

**Comment by acki-m** [comment]
´value_2 = value;  //compile error´ you cannot assign a value to a reference in C++
That's not how C++ works.
But however, I could indeed add another method to return a non-const reference to the internal value.
Atm. `value_2` is always a const reference.

**Comment by rovingstar** [comment]
Hi,

the compile error is because it's a **const** reference.  I think in C++ we can assign a value to a reference (not a const reference).

```
int a,
int& ra = a;
const int& cra = a;
ra = 20; //compile ok, same as a = 20
cra = 20; //compile error, const reference cannot be assigned.
```

but anyway, thank you for kind reply, it's really helpful.  I have modify my get_wrapped_value() to return a non const reference and it works for me.

thank you.

**Comment by acki-m** [comment]
@rovingstar 
You are right.
