### ISSUE TITLE
invoke constructor over pre-allocated memory

### ISSUE THREAD

**Issue by rovingstar** [rttrorg/rttr#168]
Hello,

is there a way to invoke constructor over pre-allocated memory address instead of allocating inside constructor::invoke

just like:

`void* operator new (std::size_t size, void* ptr)`

Thank you.

**Comment by acki-m** [comment]
you can register a free or static function as constructor
[registration::constructor](http://www.rttr.org/doc/master/classrttr_1_1registration_1_1class__.html#a54b2d5501df646b98a2ca0853b3752e0)
Does this help?

**Comment by acki-m** [comment]
@rovingstar 
Can you please close the issue, when its solved for you.
