### ISSUE TITLE
Link errors due to not exported std templates specializations

### ISSUE THREAD

**Issue by RohacekD** [rttrorg/rttr#170]
We run into a warning during the compilation project with dynamically linked libraries.

>warning C4251: 'rttr::detail::registration_executer::m_list': class 'std::vector<rttr::detail::registration_executer::item_type,std::allocator<_Ty>>' needs to have dll-interface to be used by clients of class 'rttr::detail::registration_executer'
>         with
>         [
>             _Ty=rttr::detail::registration_executer::item_type
>         ]
>note: see declaration of 'std::vector<rttr::detail::registration_executer::item_type,std::allocator<_Ty>>'
>         with
>         [
>             _Ty=rttr::detail::registration_executer::item_type
>         ]
>warning C4251: 'rttr::registration::m_reg_exec': class 'std::shared_ptr<rttr::detail::registration_executer>' needs to have dll-interface to be used by clients of class 'rttr::registration'
>note: see declaration of 'std::shared_ptr<rttr::detail::registration_executer>'

We fixed this by changing the order of includes - which is a very tedious and inconvenient way.
The second solution we figured out is exporting this two specializations like this:

#registration.h
```
#ifdef RTTR_DLL
template class RTTR_API std::shared_ptr<detail::registration_executer>;
#endif
```

Which approach is prefered, or can I prepare to pull request with this exports? Or maybe there is some problem with includes somewhere else?

**Comment by acki-m** [comment]
Do you have a small test case, so that I can analyze this problem?

**Comment by RohacekD** [comment]
I've got file setUiName.cpp which looks like this:

```cpp
#include <rttr/type.h>
#include <rttr/instance.h>
#include <rttr/rttr_cast.h>
#include <rttr/registration.h>

#include <SetUiName.h>

//==============================================================================
RTTR_REGISTRATION
{

	rttr::registration::class_<C_SetUiName>("setUiName")
		.constructor<>()(rttr::policy::ctor::as_std_shared_ptr)
		.property("name", &C_SetUiName::m_name);
	
	rttr::type::register_wrapper_converter_for_base_classes<std::shared_ptr<C_SetUiName>>();
}
```

With this header:

```cpp
#include <Operator.h>

#include <rttr/rttr_enable.h>
#include <rttr/registration_friend.h>

class C_SetUiName : public I_Operator
{
public:
...
private:
	std::string m_name;
	
	RTTR_ENABLE(I_Operator);

	RTTR_REGISTRATION_FRIEND;
};
```
And finally Operator.h includes only this and contains Operator interface:


```cpp
#include <rttr/rttr_enable.h>
#include <rttr/registration_friend.h>

class I_Operator
{
public:
	virtual ~I_Operator() = default;
	...

protected:
	RTTR_ENABLE();
};
```
And maybe just for fill the whole picture, here is Operator.cpp with RTTR_REGISTRATION:
```cpp
#include <rttr/registration.h>

#include <Operator.h>

//==============================================================================
RTTR_REGISTRATION
{
	rttr::registration::class_<I_Operator>("operation");
}
```

I tried to simplify it as much as possible. Also note that RTTR lives in different DLL in our project.

**Comment by acki-m** [comment]
First of all, you never include header of RTTR which contain a `.h` suffix.
These are the only three at the moment.
```
#include <rttr/registration> // include only this file, when you use the macro RTTR_REGISTRATION
#include <rttr/type> // include only this file, when you work with types, or props, or methods or need the place the macro RTTR_ENABLE
#include <rttr/registration_friend> // when you need to register private functions
```
All other headers will be included automatically. I should really place them into a `detail` folder.
You can also look into RTTR examples and unit tests, how is it done there.

Anyway, I need a fully functional test case in order to debug the problem. You can also play with the CMake project of RTTR and send me a branch which can reproduce the problem?

**Comment by RohacekD** [comment]
Our project generator doesn't put headers without ".h" inside our projects, so we missed them. And also we were a little bit confused by Doxygen documentation, which put .h headers everywhere. 

All our build errors are fixed by just switching to the headers you described. Ok, thank you. Very much, IMHO we can close this issue.
