### ISSUE TITLE
can't deserialize std::vector<std::string> using the json wrapper

### ISSUE THREAD

**Issue by nedway** [rttrorg/rttr#171]
deserializing a std::vector\<std::string\> consistently fills out only the 1th element of the array

adding a vector of six strings to the circle class in the json_example will output correctly as 
{
    "visible": true,
    "color": "red",
    "name": "Circle #1",
    "position": {
        "x": 12,
        "y": 66
    },
...
    "stringTest": [
        "One",
        "Two",
        "Three",
        "Four",
        "Five",
        "Six"
    ]
}

but deserializes to c_2 as 

Circle c_2:
{
    "visible": true,
    "color": "red",
    "name": "Circle #1",
    "position": {
        "x": 12,
        "y": 66
    },
...
    "stringTest": [
        "",
        "Two",
        "",
        "",
        "",
        ""
    ]
}

I am using msvc 2015, x64

**Comment by acki-m** [comment]
@nedway 
Can you you please post the changed code?
So I can debug correctly.

**Comment by nedway** [comment]
`
main.cpp replacement for json_serialization example

[main.zip](https://github.com/rttrorg/rttr/files/2189674/main.zip)

`
