### ISSUE TITLE
How to support android & ios build?

### ISSUE THREAD

**Issue by kinglezhuang** [rttrorg/rttr#176]
I can not build on iOS & Android.
Can you support them?

**Comment by acki-m** [comment]
I would like too, any patch is welcome. But I don't have the resources at the moment. Did you try to build it, what are the errors?

**Comment by kinglezhuang** [comment]
You can refer to: https://github.com/dropbox/djinni
It contains iOS & Android build script & cmakefiles

**Comment by kinglezhuang** [comment]
lmxmn212:rttr-master kingle.zhuang$ ./ios-build-support-lib.sh 
Checking build directory...
Checking output directory...
Building Native OS
-- Building with Xcode version: 9.4.1
-- Configuring iOS build for platform: OS, architecture(s): armv7;armv7s;arm64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk for platform: OS
-- Using the default min-version since IOS_DEPLOYMENT_TARGET not provided!
-- Enabling ARC support by default. ENABLE_ARC not provided!
-- Hiding symbols visibility by default. ENABLE_VISIBILITY not provided!
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using a data_ptr size of 4
-- Building for minimum iOS version: 10.0 (SDK version: 11.4)
-- Version flags set to: -miphoneos-version-min=10.0
-- Enabling bitcode support.
-- Enabling ARC support.
-- Hiding symbols (-fvisibility=hidden).
-- Building with Xcode version: 9.4.1
-- Configuring iOS build for platform: OS, architecture(s): armv7;armv7s;arm64
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using a data_ptr size of 4
-- Building for minimum iOS version: 10.0 (SDK version: 11.4)
-- Version flags set to: -miphoneos-version-min=10.0
-- Enabling bitcode support.
-- Enabling ARC support.
-- Hiding symbols (-fvisibility=hidden).
-- The CXX compiler identification is AppleClang 9.1.0.9020039
Project version: 0.9.7
-- Architecture: x86
-- Enabled: use of RTTI
-- Performing Test HAS_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT
-- Performing Test HAS_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT - Success
-- Performing Test HAS_STL_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT
-- Performing Test HAS_STL_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT - Success
-- Performing Test HAS_CXX_CONSTEXPR
-- Performing Test HAS_CXX_CONSTEXPR - Success
-- Performing Test HAS_PARTIAL_SPECIALIZATION_FOR_ARRAYS
-- Performing Test HAS_PARTIAL_SPECIALIZATION_FOR_ARRAYS - Success
-- using C++: 17
-- 
-- Finding 3rd party libs...
-- ===========================
-- Finished finding 3rd party libs!
CMake Warning at CMake/installer.cmake:60 (message):
  This system is not supported for packing
Call Stack (most recent call first):
  CMakeLists.txt:79 (include)


-- Scanning rttr module.
-- ===========================
-- rttr directory included
CMake Error at src/rttr/CMakeLists.txt:63 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "AppleClang"

  version 9.1.0.9020039.


-- Scanning rttr module finished!
-- 
-- Scanning unit_tests module.
-- ===========================
-- unit_tests directory included
-- Scanning unit_test_plugin module.
-- ===========================
-- plugin directory included
-- Scanning unit_test_plugin module finished!
-- 
-- Scanning unit_tests module finished!
-- 
-- Scanning json_example module.
-- ===========================
-- files directory included
-- Scanning json_example module finished!
-- 
-- Scanning library_loader_example module.
-- ===========================
-- files directory included
-- Scanning library_loader_example module finished!
-- 
-- Scanning plugin_example module.
-- ===========================
-- files directory included
-- Scanning plugin_example module finished!
-- 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Warning at doc/CMakeLists.txt:85 (message):
  Doxygen not found - Documentation will not be generated!


-- Configuring incomplete, errors occurred!
See also "/Users/kingle.zhuang/Desktop/rttr-master/build/build_OS/CMakeFiles/CMakeOutput.log".
See also "/Users/kingle.zhuang/Desktop/rttr-master/build/build_OS/CMakeFiles/CMakeError.log".
make: *** No rule to make target `install'.  Stop.
cp: /Users/kingle.zhuang/Desktop/rttr-master/build/build_OS/libpugixml.a: No such file or directory
Copy header files...
cp: /Users/kingle.zhuang/Desktop/rttr-master/build/build_OS/build_OS/include: No such file or directory
Building Native SIMULATOR64
-- Building with Xcode version: 9.4.1
-- Configuring iOS build for platform: SIMULATOR64, architecture(s): x86_64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk for platform: SIMULATOR64
-- Using the default min-version since IOS_DEPLOYMENT_TARGET not provided!
-- Enabling ARC support by default. ENABLE_ARC not provided!
-- Hiding symbols visibility by default. ENABLE_VISIBILITY not provided!
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using a data_ptr size of 8
-- Building for minimum iOS version: 10.0 (SDK version: 11.4)
-- Version flags set to: -mios-simulator-version-min=10.0
-- Enabling bitcode support.
-- Enabling ARC support.
-- Hiding symbols (-fvisibility=hidden).
-- Building with Xcode version: 9.4.1
-- Configuring iOS build for platform: SIMULATOR64, architecture(s): x86_64
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using a data_ptr size of 8
-- Building for minimum iOS version: 10.0 (SDK version: 11.4)
-- Version flags set to: -mios-simulator-version-min=10.0
-- Enabling bitcode support.
-- Enabling ARC support.
-- Hiding symbols (-fvisibility=hidden).
-- The CXX compiler identification is AppleClang 9.1.0.9020039
Project version: 0.9.7
-- Architecture: x64
-- Enabled: use of RTTI
-- Performing Test HAS_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT
-- Performing Test HAS_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT - Success
-- Performing Test HAS_STL_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT
-- Performing Test HAS_STL_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT - Success
-- Performing Test HAS_CXX_CONSTEXPR
-- Performing Test HAS_CXX_CONSTEXPR - Success
-- Performing Test HAS_PARTIAL_SPECIALIZATION_FOR_ARRAYS
-- Performing Test HAS_PARTIAL_SPECIALIZATION_FOR_ARRAYS - Success
-- using C++: 17
-- 
-- Finding 3rd party libs...
-- ===========================
-- Finished finding 3rd party libs!
CMake Warning at CMake/installer.cmake:60 (message):
  This system is not supported for packing
Call Stack (most recent call first):
  CMakeLists.txt:79 (include)


-- Scanning rttr module.
-- ===========================
-- rttr directory included
CMake Error at src/rttr/CMakeLists.txt:63 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "AppleClang"

  version 9.1.0.9020039.


-- Scanning rttr module finished!
-- 
-- Scanning unit_tests module.
-- ===========================
-- unit_tests directory included
-- Scanning unit_test_plugin module.
-- ===========================
-- plugin directory included
-- Scanning unit_test_plugin module finished!
-- 
-- Scanning unit_tests module finished!
-- 
-- Scanning json_example module.
-- ===========================
-- files directory included
-- Scanning json_example module finished!
-- 
-- Scanning library_loader_example module.
-- ===========================
-- files directory included
-- Scanning library_loader_example module finished!
-- 
-- Scanning plugin_example module.
-- ===========================
-- files directory included
-- Scanning plugin_example module finished!
-- 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Warning at doc/CMakeLists.txt:85 (message):
  Doxygen not found - Documentation will not be generated!


-- Configuring incomplete, errors occurred!
See also "/Users/kingle.zhuang/Desktop/rttr-master/build/build_SIMULATOR64/CMakeFiles/CMakeOutput.log".
See also "/Users/kingle.zhuang/Desktop/rttr-master/build/build_SIMULATOR64/CMakeFiles/CMakeError.log".
make: *** No rule to make target `install'.  Stop.
cp: /Users/kingle.zhuang/Desktop/rttr-master/build/build_SIMULATOR64/libpugixml.a: No such file or directory
Copy header files...
cp: /Users/kingle.zhuang/Desktop/rttr-master/build/build_SIMULATOR64/build_SIMULATOR64/include: No such file or directory
Building Native SIMULATOR
-- Building with Xcode version: 9.4.1
-- Configuring iOS build for platform: SIMULATOR, architecture(s): i386
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk for platform: SIMULATOR
-- Using the default min-version since IOS_DEPLOYMENT_TARGET not provided!
-- Enabling ARC support by default. ENABLE_ARC not provided!
-- Hiding symbols visibility by default. ENABLE_VISIBILITY not provided!
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using a data_ptr size of 4
-- Building for minimum iOS version: 10.0 (SDK version: 11.4)
-- Version flags set to: -mios-simulator-version-min=10.0
-- Enabling bitcode support.
-- Enabling ARC support.
-- Hiding symbols (-fvisibility=hidden).
-- Building with Xcode version: 9.4.1
-- Configuring iOS build for platform: SIMULATOR, architecture(s): i386
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using a data_ptr size of 4
-- Building for minimum iOS version: 10.0 (SDK version: 11.4)
-- Version flags set to: -mios-simulator-version-min=10.0
-- Enabling bitcode support.
-- Enabling ARC support.
-- Hiding symbols (-fvisibility=hidden).
-- The CXX compiler identification is AppleClang 9.1.0.9020039
Project version: 0.9.7
-- Architecture: x86
-- Enabled: use of RTTI
-- Performing Test HAS_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT
-- Performing Test HAS_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT - Success
-- Performing Test HAS_STL_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT
-- Performing Test HAS_STL_NO_EXCEPT_TYPE_SIGNATURE_SUPPORT - Success
-- Performing Test HAS_CXX_CONSTEXPR
-- Performing Test HAS_CXX_CONSTEXPR - Success
-- Performing Test HAS_PARTIAL_SPECIALIZATION_FOR_ARRAYS
-- Performing Test HAS_PARTIAL_SPECIALIZATION_FOR_ARRAYS - Success
-- using C++: 17
-- 
-- Finding 3rd party libs...
-- ===========================
-- Finished finding 3rd party libs!
CMake Warning at CMake/installer.cmake:60 (message):
  This system is not supported for packing
Call Stack (most recent call first):
  CMakeLists.txt:79 (include)


-- Scanning rttr module.
-- ===========================
-- rttr directory included
CMake Error at src/rttr/CMakeLists.txt:63 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "AppleClang"

  version 9.1.0.9020039.


-- Scanning rttr module finished!
-- 
-- Scanning unit_tests module.
-- ===========================
-- unit_tests directory included
-- Scanning unit_test_plugin module.
-- ===========================
-- plugin directory included
-- Scanning unit_test_plugin module finished!
-- 
-- Scanning unit_tests module finished!
-- 
-- Scanning json_example module.
-- ===========================
-- files directory included
-- Scanning json_example module finished!
-- 
-- Scanning library_loader_example module.
-- ===========================
-- files directory included
-- Scanning library_loader_example module finished!
-- 
-- Scanning plugin_example module.
-- ===========================
-- files directory included
-- Scanning plugin_example module finished!
-- 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Warning at doc/CMakeLists.txt:85 (message):
  Doxygen not found - Documentation will not be generated!


-- Configuring incomplete, errors occurred!
See also "/Users/kingle.zhuang/Desktop/rttr-master/build/build_SIMULATOR/CMakeFiles/CMakeOutput.log".
See also "/Users/kingle.zhuang/Desktop/rttr-master/build/build_SIMULATOR/CMakeFiles/CMakeError.log".
make: *** No rule to make target `install'.  Stop.
cp: /Users/kingle.zhuang/Desktop/rttr-master/build/build_SIMULATOR/libpugixml.a: No such file or directory
Copy header files...
cp: /Users/kingle.zhuang/Desktop/rttr-master/build/build_SIMULATOR/build_SIMULATOR/include: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/kingle.zhuang/Desktop/rttr-master/out/apple/*.a (No such file or directory)

**Comment by kinglezhuang** [comment]
-- using C++: 17

I don't want to C++17, just want to use C++ 11, but the makefile get the lastest C++ compiler.

**Comment by kinglezhuang** [comment]
Doxygen not found - Documentation will not be generated!

But i installed it by [brew install doxygen]

**Comment by kinglezhuang** [comment]
[buildscript.zip](https://github.com/rttrorg/rttr/files/2212200/buildscript.zip)
It's my build script

**Comment by kinglezhuang** [comment]
refer to:https://github.com/catboost/catboost/blob/master/util/system/platform.h
If i want to support arm64, should i need to change the RTTR_ARCH_TYPE detection to below code.

/////////////////////////////////////////////////////////////////////////////////////////
// Architecture
/////////////////////////////////////////////////////////////////////////////////////////
#if defined(__x86_64__) || defined(_M_X64) || defined(__powerpc64__) || defined(__alpha__) ||\
    defined(__ia64__) || defined(__s390__) || defined(__s390x__) || (defined(__arm__) || defined(__ARM__) || defined(__ARM_NEON) || defined(__aarch64__) || defined(_M_ARM) && defined(__arm64) || defined(__arm64__) || defined(__aarch64__))
#   define RTTR_ARCH_TYPE RTTR_ARCH_64
#else
#   define RTTR_ARCH_TYPE RTTR_ARCH_32
#endif

I found above code just use for testing. The source code do not consume RTTR_ARCH_TYPE

**Comment by acki-m** [comment]
> I don't want to C++17, just want to use C++ 11, but the makefile get the lastest C++ compiler.
Yeah, I need to fix this. So that you can provide also manually the used C++ standard.

Anyway, can you not provide your changes via a PR?
Here is some guide how you can test android: https://docs.travis-ci.com/user/languages/android/
Make one PR for one system. So I would start with android.

**Comment by kinglezhuang** [comment]
I committed the build script on my github: https://github.com/kinglezhuang/DCPS/tree/master/script/reflection

But it have some issues about can not found symbols when linking, so i changed to Xcode build system to generate iOS library

**Comment by acki-m** [comment]
@kinglezhuang 
Any updates here?

**Comment by acki-m** [comment]
I close, because I didn't get any update, fee free to open it, when you have some PR to merge
