### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by marcospampi** [rttrorg/rttr#179]
I'm testing rttr, whenever my code execution ends (it works as expected), a segmentation fault happens.
Using gdb I get this seg fault log
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000418812 in std::unique_ptr<rttr::detail::property_wrapper_base, std::default_delete<rttr::detail::property_wrapper_base> >::~unique_ptr() ()
(gdb) step
Single stepping until exit from function _ZNSt10unique_ptrIN4rttr6detail21property_wrapper_baseESt14default_deleteIS2_EED2Ev,
which has no line number information.

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.

```
The program actually runs, using rttr too.

I've read rttr uses to execute its code before main(), and so it could be releasing itself after main exits, this is where I think it'd fails to do so.

Compiler is g++
```
g++ (Ubuntu 7.3.0-21ubuntu1~16.04) 7.3.0
```

**Comment by acki-m** [comment]
Every code, which gets merged into master, will run through several CI tests.
E.g.: https://travis-ci.org/rttrorg/rttr/jobs/404230420
This will run valgrind. No error so far.
So in order to reproduce the issue, I need a minimal test case from you.

**Comment by acki-m** [comment]
@marcospampi 
When you have no test case or fixed your issue yourself, please close the issue.

**Comment by marcospampi** [comment]
I'm closing the issue since I solved it, I've just made the library embedded.
Though my test case is all about a single include with standard settings and cmake's include dir and target link
