### ISSUE TITLE
is_associative_view returns false when invoked on an instance of std::map

### ISSUE THREAD

**Issue by NikolaMr** [rttrorg/rttr#193]
Hi!

I have a problem with the associative_view.
The problem can be seen when running the following snippet:

```
std::map < std::string, std::string> asset;
asset["bok"] = "";
asset["hi"] = "";
asset["hy"] = "";

rttr::instance instance = asset;
const rttr::type value_t = instance.get_type();
const rttr::variant var = value_t;
rttr::variant_associative_view assocView = var.create_associative_view();
bool isAssociativeView = assocView.is_valid();
```

After running this snippet, isAssociativeView is equal to false when it should be true since the map is an associative container.

However, the following code snippet:

```
std::map < std::string, std::string> asset;
asset["bok"] = "";
asset["hi"] = "";
asset["hy"] = "";

rttr::variant var_s = asset;
bool isAssociativeView = var_s.is_associative_container();
```

In this case, isAssociativeView is true.

Is this the expected behavior? Is there a workaround?
This problem is manifested when I try to write to a json file and read from a json file my own class that has a map as an attribute.

**Comment by acki-m** [comment]
@NikolaMr 
That's not how it works.

```
const rttr::type value_t = instance.get_type();
const rttr::variant var = value_t;
```
With this code, you basically store a type inside a variant, but not the value itself.
So a `rttr:.type` is stored and this is of course not an associative view.

What you can do, is also this:
```
std::map < std::string, std::string> asset;
rttr::variant var_s = std::ref(asset);
bool isAssociativeView = var_s.is_associative_container();
```
Then no dynamic memory will be allocated, the view will work directly on your object `asset`, which you have provided.

Does this help?

**Comment by NikolaMr** [comment]
Thank you for the explanation. This makes it clearer to me. 
Once again, thank you!

Best regards,
Nikola
