### ISSUE TITLE
gsl::span as property type

### ISSUE THREAD

**Issue by bschindler** [rttrorg/rttr#194]
Hi 
I am in the situation, that I have to expose a class using rttr which uses a pimpl. Inside the pimpl there is a std::vector<int> and due to abi safety reasons, the get/set methods use gsl::span. 
As a result, I'm trying to get this to work but the first issue I'm facing is that rttr::variant is then forced to "store a span". But since span doesn't own the memory, I'd have to have the variant allocate a std::vector if given a gsl::span. 

Is having properties on gsl::span something that is feasible at all in rttr?

**Comment by acki-m** [comment]
What is the problem with storing a span inside a `rttr::variant`? It is actually quite good not to copy the whole vector.

**Comment by bschindler** [comment]
So the following code which I'd intuitively expect to work doesn't: 

```
class SpanTestClass
{
	RTTR_ENABLE()
	
public:
	gsl::span<int> vec() { return _data; }
	void setVec(gsl::span<int> points) { _data.assign(points.begin(), points.end()); }
	
private:
	std::vector<int> _data;
};
RTTR_REGISTRATION
{
	using namespace rttr;

	// clang-format off
	registration::class_<SpanTestClass>("SpanTestClass")
		.constructor<>()
		.property("IntVec", &SpanTestClass::vec, &SpanTestClass::setVec);
	// clang-format on
}

TEST(SerializationTest, SpanTest)
{
	SpanTestClass inst;
	rttr::type t = rttr::type::get_by_name("SpanTestClass");
	auto prop = t.get_property("IntVec");
	std::vector<int> vec = {1, 2, 3};
	rttr::variant v(gsl::span<int>(vec));
	prop.set_value(inst, vec);
	std::vector<int> result;
	auto span = inst.vec();
	result.assign(span.begin(), span.end());
	EXPECT_EQ(vec, result);
}
```

**Comment by acki-m** [comment]
So when you are good, can you close the issue?

**Comment by acki-m** [comment]
I will close the issue now.
