### ISSUE TITLE
crash on process termination with mutual base class

### ISSUE THREAD

**Issue by jackgan90** [rttrorg/rttr#199]
There seems to be a bug related to type unregistration when the process terminates.Said I have a base class named CommonBase which is inherited by Derived1 and Dervied2.All of the 3 classes have RTTR_ENABLE declared.Derived1 and Derived2 lie in different dlls. When the process terminates,both types will be unregistered as well as CommonBase.Now the problem is: suppose dll1 which hosts CommonBase and Derived1 detaches from the process first.Then CommonBase  will be unregistered from type_register.
After that, dll2 detaches from the process,causing Derived2 to unregister its type from type_register.But at that moment,CommonBase is already unregistered.My program crashes at type_register_private::remove_derived_types_from_base_classes,because the base_types holds invalid data here.
from what I understand,if I can ensure all derived classes are unregistered first,and base classes later, I can make the behavior correct.But that may add lots of complexity for my program.So is it a BUG or just a design decision to have this behavior?Point me out if there's something I miss.

My test platform is Windows10 with visual studio 2015

**Comment by acki-m** [comment]
This sounds like a bug. Can you please provide a stand alone test case for this?

**Comment by jackgan90** [comment]
Sure, this is a minimal project I made to show the problem.
[rttr_unregistration.zip](https://github.com/rttrorg/rttr/files/2560158/rttr_unregistration.zip)

**Comment by acki-m** [comment]
Okay, i can confirm the crash. I had several issue setting up the cmake project. Always get a strange linker error. Had to remove this call here: `project(rttr_unregistration)`

I will now take a look into it.
