### ISSUE TITLE
Add support for new property policy: 'as_reference_wrapper'

### ISSUE THREAD

**Issue by acki-m** [rttrorg/rttr#20]
Add a new property policy called: `as_reference_wrapper` or similar.
Which should return the property as inside a `std::reference_wrapper`.
The wrapped type can be retrieve later via `type::get_wrapped_type()`.

This policy is similar to `bind_as_ptr`, however somebody might prefer a solid wrapper, instead of a raw ptr.

**Comment by sbalogh** [comment]
Please add a `as_reference_wrapper` policy like possibility to access variant_array_view elements. 
It would be very useful to prevent a copy of "big" elements and sub arrays.

How can we access wrapped value and conversion functions of variant with wrapped types? 
Value can be accessed if using instance class and instance::try_convert function, but instance conversion functions (to_string, to_int, ...) do not exist.

**Comment by acki-m** [comment]
merged into master
