### ISSUE TITLE
override rttr_core's memory allocation

### ISSUE THREAD

**Issue by rovingstar** [rttrorg/rttr#201]
Hello, 
I'm trying to integrating global memory management in my project (for better profiling & leak detection).  I'm doing it by override new/delete operators.  But here is the problem:  the registration code in my cpp is overridden but the code in rttr_core is not (still using standard memory allocation), and it will cause crash.  Is there a way to register memory allocation method in rttr_core  without update it's code to override the defaults like many 3rd party libraries do?

**Comment by acki-m** [comment]
you can provide for constructors custom lambda function, which does the allocation there.
But there is no way at the moment in order to do that with all the other allocations.
When you have an idea how to do that, just tell me before implementing it.

**Comment by rovingstar** [comment]
OK thanks.  I'll try something my self at this moment.  I will let you if it works for me.  Thanks. :)
