### ISSUE TITLE
Variant initialize

### ISSUE THREAD

**Issue by rovingstar** [rttrorg/rttr#203]
hello,

I want to initialize a variant to a certain type's default value (return invalid variant if the type doesn't have default constructor).  How do I do it?

something like:
`rttr::variant getDefaultValue(rttr::type _type)`
`{`
`    //return the default value of _type`
`}`

Thank you,
Xu.

**Comment by acki-m** [comment]
You should not create invalid types. That's why it is not possible by default.

**Comment by rovingstar** [comment]
Hi,

I'm not trying to create invalid types.  I mentioned invalid variant.
And variant by default is invalid I think...

**Comment by rovingstar** [comment]
OK, sorry for not being clear.

I want to write a function, as described below:

```
rttr::variant defaultValue(rttr::type _type)
{
//return the default value of _type as a variant.  If the type doesn't have a default constructor, then return invalid variant
}

```

I'm not sure if it's clear enough.  All I need is to initialize a variant with certain rttr type....

**Comment by acki-m** [comment]
here is a workaround:
```
rttr::variant defaultValue(rttr::type _type)
{
    return rttr::type::get_by_name("");
}
```
But I don't know what you really want to do with it...

**Comment by rovingstar** [comment]
OK, I didn't describe it clear enough, sorry.  Basically, I want a rttr version of this function:

```
template <typename T> rttr::variant defaultValue()
{
    T t;
    return t;
}
```
