### ISSUE TITLE
Reload plugin. rttr::policy::ctor::as_object Debug Assertion Failed!

### ISSUE THREAD

**Issue by EugeneGribovich** [rttrorg/rttr#210]
Hello.
1. We have a plugin that can be reloaded at runtime. 
2. We have shared header file with POD structure included in the plugin and in the main application
3. Plugin registers the POD structure with rttr::policy::ctor::as_object
4. The main app creates rttr::variant from the structure and creates rttr::instance from the rttr::variant. Afrer the it reloads the plugin and we have 

Debug Assertion Failed!

Program: ...49-7b0ed7eddcb5\build\x64-Debug (default)\bin\rttr_core_d.dll
File: c:\program files (x86)\microsoft visual studio\2017\professional\VC\Tools\MSVC\14.16.27023\include\xutility
Line: 559

Expression: transposed pointer range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

Thank you
Example attached:
[rttr.zip](https://github.com/rttrorg/rttr/files/2647981/rttr.zip)

**Comment by acki-m** [comment]
That's not how a plugin works. When you have a plugin, you can't instantiate the type like you did:
`rttr::variant vÑomp = PluginComponent{};`

What you have to do is following:
```
    auto t = type::get_by_name("PluginComponent");
    rttr::variant vÑomp = t.create();
    
    rttr::instance compInst(vÑomp);
```
Then you don't get any assert error anymore. Take also a look in the unit test for the plugin, there it gets loaded multiple times.
You can only interact over RTTR with your plugin type.
Does this solve your problem?

**Comment by acki-m** [comment]
I close this, it seems to be solved for your.
