### ISSUE TITLE
Generate The rttr code with tools?

### ISSUE THREAD

**Issue by molixiaoge** [rttrorg/rttr#24]
I found the similar project,the url is https://github.com/AustinBrunkhorst/CPP-Reflection
So ,i think if use it to generator your rttr code,then everythings will gonna to be easy and fast.

**Comment by acki-m** [comment]
Why do you think it will be easy and fast?

**Comment by molixiaoge** [comment]
It's just a suggestion,i do not know the difficult level.Maybe I'm wrong.
