### ISSUE TITLE
Unresolved external symbols..

### ISSUE THREAD

**Issue by edin-p** [rttrorg/rttr#25]
Hi.. first of all looks like an awesome lib but i have some problems linking it.. 
Whichever lib i link from the 7z archive from the download section of your site i get unresolved external symbols.. i use VisualStudio and trying to link the lib to my 3D engine which is an DLL.. have no idea how to fix it and i don't use cmake so could not follow your last step in "Instal" section 

And one question i have is will the registered classes be available to my 3D Editor if i link your lib both to the engine and editor as static library and if not how to change that? 

Thanks!

**Comment by acki-m** [comment]
1)
I recommend to use cmake for using RTTR. However, it must work also without it.
Did you linked against the `.lib` file? For example for a debug build: `\rttr-0.9.5-win64-vs2013\lib\rttr_core_d.lib` for the dynamic debug build.
2)
It should work, when your 3d Editor and your engine are in the same process.

**Comment by edin-p** [comment]
I did, i tried every .lib but the result is same.. bunch of unresolved externals..

**Comment by edin-p** [comment]
For some reason I managed it to work by using #pragma comment(lib, ...) so i can link now dynamic lib.. but still can't static..

**Comment by acki-m** [comment]
CMake does simplify this job a lot for you, I can only recommend it for you.
I think the problem is, you didn't defined: `RTTR_DLL`
When you link dynamically against the library, this macro needs to be defined, otherwise, statically, nothing needs to be defined (but of course you have to link against another library).

**Comment by Cccrisppp** [comment]
> CMake does simplify this job a lot for you, I can only recommend it to you.
> I think the problem is, you didn't defined: `RTTR_DLL`
> When you link dynamically against the library, this macro needs to be defined, otherwise, statically, nothing needs to be defined (but of course you have to link against another library `librttr_core.lib`).
> Remove the `#pragma comment(lib, ...)` that's not necessary

How do I define RTTR_DLL (I have added it to the environment variable)?
