### ISSUE TITLE
Register a class ("mclass") with the custom name ("mymclass") witch contains a raw name ("mclass") causes the type get_name() return a wrong name ("mymymclass")

### ISSUE THREAD

**Issue by sbalogh** [rttrorg/rttr#27]
The patch below solves the problem  for me.

```
diff --git a/src/rttr/detail/type/type_register.cpp b/src/rttr/detail/type/type_register.cpp
index 332fff2..2afc182 100644
--- a/src/rttr/detail/type/type_register.cpp
+++ b/src/rttr/detail/type/type_register.cpp
@@ -440,7 +440,7 @@ void type_register_private::register_custom_name(type& t, string_view custom_nam
     auto tmp_type_list = custom_name_to_id.value_data();
     for (auto& tt : tmp_type_list)
     {
-        if (tt.get_raw_array_type() == t)
+        if (tt.get_raw_array_type() == t && tt != t)
         {
             const auto& orig_name_derived = tt.m_type_data->name;
             custom_name_to_id.erase(orig_name_derived);

```
[type_register.diff.zip](https://github.com/rttrorg/rttr/files/614777/type_register.diff.zip)

**Comment by acki-m** [comment]
Can you please give me the registration code, i.e. a test case?

**Comment by sbalogh** [comment]
Test case code is attached.

[main.cpp.zip](https://github.com/rttrorg/rttr/files/615077/main.cpp.zip)

**Comment by acki-m** [comment]
This is the output I get with the latest version:
```
Name:myshape
Name:circleyour
Name:mypoint2d
Name:mycolor
```
Seems good to me. Or am I missing something?

**Comment by sbalogh** [comment]
It is interesting. I get with the git master:
```
Name:mymyshape
Name:circleyouryour
Name:mymypoint2d
Name:mymycolor
```
I think this is the "right" behavior, because without the patch in the `type_register_private::register_custom_name` function the type_data.name firstly is assigned to a new custom name for the given type `t` ([line1](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/type/type_register.cpp#L434)). After that  in the for loop  old raw names are replaced with new custom name  for all type including for the given type `t` with an already updated  type_data.name ([line2](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/type/type_register.cpp#L448)).

**Comment by acki-m** [comment]
what compiler do you use?

**Comment by sbalogh** [comment]
I'm using g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609 on Ubuntu 16.04.
I was surprised your output.
