### ISSUE TITLE
how to  print  values of all member fields of a struct?

### ISSUE THREAD

**Issue by dbsxdbsx** [rttrorg/rttr#273]
I read pretty many examples about rttr.  It seems that registration have to be done before anything further, like this:
```
#include <rttr/registration>
using namespace rttr;

struct MyStruct { MyStruct() {}; void func(double) {}; int data; };

RTTR_REGISTRATION
{
    registration::class_<MyStruct>("MyStruct")
         .constructor<>()
         .property("data", &MyStruct::data)
         .method("func", &MyStruct::func);
}
```
but  what I want is to print  values of all member fields of a struct instance,  it seems that the below code is related:
```
type t = type::get<MyStruct>();
for (auto& prop : t.get_properties())
    std::cout << "name: " << prop.get_name();
```
But it only works for  type information, not instance.

what I want is some code like this:
```
for (auto& prop : instance.get_properties())
    std::cout << "name: " << prop.get_name()<< "value:"<<prop.get_value()<<std::endl;
```
is it feasible with rttr? And can the `RTTR_REGISTRATION` part be removed,as it looks quite tedious.

**Comment by atokama** [comment]
You can get rttr::type from an instance (dynamically) and then
use it to get properties:
````
MyStruct s{};
type t= type::get(s);
for (auto& prop : t.get_properties())
    std::cout << "name: " << prop.get_name();
````

(I'm also newbie.)

**Comment by dbsxdbsx** [comment]
@atokama, thanks, I would give it a try.
