### ISSUE TITLE
Scripting example

### ISSUE THREAD

**Issue by amerkoleci** [rttrorg/rttr#28]
Would be possible to show some rttr usage in scripting language context?
IE: Binding to lua or something else.

Thanks

**Comment by ArnCarveris** [comment]
To implement binding support, there need pubic access to property & function/method memory offset or raw pointer address, also for variant there need raw pointer address.

**Comment by Xipiryon** [comment]
Resurrecting a one year old thread, but maybe you could have a look at what Selene guys did 
( https://github.com/jeremyong/Selene ). 

I'm wondering if rttr should be strongly tied to a specific script language, or if it'd be better to have a virtual interface to specialize (like for people that prefer angelscript / chaiscript / python / etc... over lua).

**Comment by acki-m** [comment]
@Xipiryon 
What did the Selene guys did?
This library here: https://github.com/ThePhD/sol2
Seems to me the most promising one for binding to lua, IMHO.

I am working on a generic visitor mechanism, which lets you bind you're registered classes at compile time to other libraries. I will link the PR here.

However, having direct support (against the runtime interface of RTTR) for one scripting language (e.g. Lua) would be interesting. I don't know how extensive the work would be..

**Comment by ArnCarveris** [comment]
@acki-m Just give absolute address & offsets API.

**Comment by acki-m** [comment]
can you elaborate what do you mean?

**Comment by ArnCarveris** [comment]
@acki-m Need some kind of API for getting address/offset from [property(m_acc's)](https://github.com/rttrorg/rttr/blob/07c3c94275e2bde73f6da8e572eb463af4202721/src/rttr/detail/property/property_wrapper_member_object.h#L121), [method(m_func_acc's)](https://github.com/rttrorg/rttr/blob/07c3c94275e2bde73f6da8e572eb463af4202721/src/rttr/detail/method/method_wrapper.h#L123) and others.

**Comment by Xipiryon** [comment]
> @acki-m 
> This library here: https://github.com/ThePhD/sol2
> Seems to me the most promising one for binding to lua, IMHO.

SOL definitely look better than Selene in term of performance and usability (they even have a single header version !). I just didn't know about it :)

> @acki-m 
> I am working on a generic visitor mechanism, which lets you bind you're registered classes at compile time to other libraries. I will link the PR here.

I think that's the best balance between 'ease of use' and 'being able to extend possibilities'. For exemple, one could use this visitor to send data over the network instead of passing arguments to a scripting language. 
I suppose you could still just expose private attribute/member as @ArnCarveris suggest, but I'd rather have to specialize a visitor to be sure I'm not touching any internal state/data I shouldn't.

**Comment by acki-m** [comment]
@ArnCarveris 
Can you please give a code example how this should work? Because, I don't see how this should help to bind functions to other libraries.

**Comment by acki-m** [comment]
Please everyone checkout the latest source code in the master branch and try out the scripting example. It uses a compile time visitor approach to get scripting done. So not 100% dynamic, but you should be able to bind to every other scripting language without any problems (at least when they have a nice interface as RTTR ^^).
See: #153

**Comment by acki-m** [comment]
@amerkoleci 
See also the tutorial here in order to do a dynamic binding: https://www.youtube.com/watch?v=O0f7aGU61II
