### ISSUE TITLE
muliple wrapped types

### ISSUE THREAD

**Issue by matpen** [rttrorg/rttr#30]
I have used RTTR for a while now and first of all I wanted to renew my gratitude for a great library.

The issue I am facing now concerns template types with multiple template arguments.
For example pairs (e.g. std::pair<std::string, double>) or maps (e.g. std::map<std::string, double>).

Is there a way to implement a "wrapper_mapper" and/or an "array_mapper" to access the wrapped types in these cases?

**Comment by acki-m** [comment]
I am working right now on a variant_map_view. So this will come. However for the `std::pair`, you can just register the properties `first` & `second`. Then you can extract the values via a `property`. Is this okay for you?

**Comment by matpen** [comment]
Great idea: simple and effective! Yes that suits me for `std::pair`.
Then I will just wait for variant_map_view... thank you for doing that. Would you mind closing this issue after committing that change, so I get notified?
