### ISSUE TITLE
var.get_type().get_name() return std::shared_ptr<MyStruct>,not 'MyStruct'.

### ISSUE THREAD

**Issue by ThisisGame** [rttrorg/rttr#309]
`type t = type::get_by_name("MyStruct");
variant var = t.create();    // will invoke the previously registered ctor

constructor ctor = t.get_constructor();  // 2nd way with the constructor class
var = ctor.invoke();
std::cout << var.get_type().get_name(); // prints 'MyStruct'`

var.get_type().get_name() return std::shared_ptr<MyStruct>,not 'MyStruct'.

**Comment by emikita** [comment]
use  .constructor<>()(rttr::policy::ctor::as_object)
rttr::as_std_shared_ptr is the default policy
