### ISSUE TITLE
RTTR and STL/STL-like types/objects

### ISSUE THREAD

**Issue by hydexon** [rttrorg/rttr#32]
So since i was working with RTTR porting from the old library i came across another issue: STL/STL-like types and serialization of those, my projects uses types reflected in the old library such as std::string and others and my internal STL types such Map, Set, HashMap, and a bit of the EASTL and other templated classes/structs, all of those fields are serialized into JSON/Binary files at the end.

i saw in the issue #30, you're still working an solution for somewhat my problem with the `variant_map_view` approach, there's some kind of workaround, without relying with proxy classes, your already implemented `wrapper_mapper` may work for templates which has only one parameter...

Thanks you.

**Comment by acki-m** [comment]
What is your actual question?

I am close to submitting the branch. The new class will be called: `variant_associative_view` and you will be able to retrieve all data (with simple range based for loop) from an associative container, like `set`, `map`, `multimap`, `unordered_map` and of course custom classes. I am pleased, when you can give me feedback regarding the interface, when I have submitted the code.

Regarding the [wrapper_mapper](http://www.rttr.org/doc/master/structrttr_1_1wrapper__mapper.html), you wrapper class template can have as many template parameters as you want, its a partial template specialization.
```
template<typename T1, typename T2, typename T3>
struct wrapper_mapper<custom_type<T1, T2, T3>>
{
    
};
```

**Comment by hydexon** [comment]
Registering STL-like classes (the C++ standard one, EASTL and custom one), and how properly serializing it.

**Comment by acki-m** [comment]
I added a new class called `variant_associative_view`, try it out and give me some feedback when its good or you stumble about issues.
