### ISSUE TITLE
None of the versions compile for C++ 20

### ISSUE THREAD

**Issue by killereks** [rttrorg/rttr#366]
I've tried building different versions manually, and using binaries but they all result in these errors when linking it in the project:

![image](https://github.com/rttrorg/rttr/assets/10748374/10daebe5-08a1-4aa5-a90b-5f36b7de7a58)

**Comment by killereks** [comment]
Fixed, the namespace had to be added manually for each line.

**Comment by brannanz** [comment]
Having the same problem please explain

**Comment by brannanz** [comment]
Nvm figured it out what you've gotta do is in bind_impl.h replace every call to "type::get" with "rttr::type::get"
