### ISSUE TITLE
Assign metadata to a type

### ISSUE THREAD

**Issue by MicBe** [rttrorg/rttr#42]
Hello,

Is it possible to assign metadata (like we can do for properties) to a type?

I would like to do something like this:

> registration::class_<MyClass>("MyClass").metadata(UserFriendlyName, "My Class");
> 

Thanks

**Comment by acki-m** [comment]
Yes it is possible.
Something like this should work:
```
registration::class_<MyClass>("MyClass")( metadata(UserFriendlyName, "My Class") );
```

**Comment by MicBe** [comment]
Thank you!
