### ISSUE TITLE
Array types: Get value type and create new instance

### ISSUE THREAD

**Issue by jgehring** [rttrorg/rttr#49]
First, thanks for the great library! I'm looking for a way to retrieve the value type of a type of an array. For example, given `auto type = rttr::type::get<std::vector<int>>()`, how can I get a type for the array values, i.e. `int` in this case? Also, how do I create a new instance for the type above and add values to it? `type.create()` yields an invalid variant.

**Comment by acki-m** [comment]
At the moment you have to use the [variant_array_view](http://www.rttr.org/doc/master/classrttr_1_1variant__array__view.html) class to get the [rank](http://www.rttr.org/doc/master/classrttr_1_1variant__array__view.html#a3ab67960b4c4df088a9d08888c862046) of an array.
For the creation of a type, you have to register its constructor via the [registration](http://www.rttr.org/doc/master/classrttr_1_1registration.html ) class
Anyway, here is a code snippet which shows you, how to do this:
```
rttr::registration::class_<std::vector<int>>("std::vector<int>")
    .constructor<std::vector<int>::size_type, int>()
    (
        rttr::policy::ctor::as_object, // optional
        parameter_names("count", "values") // optional
    );
rttr::variant var = type::get<std::vector<int>>().create({ std::size_t(10), int(42) });
auto view = var.create_array_view();
std::cout << view.get_rank_type(1).get_name() << std::endl; // will print 'int'
```

**Comment by jgehring** [comment]
Thanks, this works!
