### ISSUE TITLE
Warning when compiling with GCC 5.4

### ISSUE THREAD

**Issue by jgehring** [rttrorg/rttr#67]
When I compile rttr with `-Wall` with gcc-5.4, I get quite a lot of warnings. Unfortunately, some of them show up in programs using the library, too. In particular, I see a similar warning than the following for files that contain an `RTTR_REGISTRATION` block:

```
In file included from /home/jgehring/tmp/rttr/src/rttr/../rttr/type.h:1152:0,
                 from /home/jgehring/tmp/rttr/src/rttr/../rttr/detail/destructor/destructor_wrapper_base.h:32,
                 from /home/jgehring/tmp/rttr/src/rttr/detail/destructor/destructor_wrapper_base.cpp:28:
/home/jgehring/tmp/rttr/src/rttr/../rttr/detail/type/type_impl.h: At global scope:
/home/jgehring/tmp/rttr/src/rttr/../rttr/detail/type/type_impl.h:489:13: warning: ‘void rttr_auto_register_reflection_function_()’ declared ‘static’ but never defined [-Wunused-function]
 static void rttr_auto_register_reflection_function_();
```

In my project, I would prefer to not turn off this warning. However, I'm not clear what the root cause in rttr is exactly.

**Comment by acki-m** [comment]
When you know a way how to temporarily disable this warning for a function, please tell me.
Otherwise I don't know how to fix it.

**Comment by acki-m** [comment]
actually, it is not possible with gcc to disable this warning temporarily:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53431
Its a known bug.
However, I fixed it with placing the RTTR_REGISTRATION_FRIEND function in a separate header file called:
`registration_friend.h`, include it with: `#include <rttr/registration_friend>`

**Comment by jgehring** [comment]
Thanks for tracking this down! The GCC bug is annoying :(
