### ISSUE TITLE
Class hierarchy description

### ISSUE THREAD

**Issue by NuckNuck** [rttrorg/rttr#75]
Hi,
is it possible to describe the base classes like properties or functions?
I can't  add the RTTR_ENABLED macro to my code base and the used 3rd party libs aren't changeable.
It would be nice to describe the class hierarchy like normal attributes

`registration::class_<MyType>("MyType")
.base<MyBase1>(registration::public_access).base<MyBase2>(registration::private_access);`

**Comment by acki-m** [comment]
It might be possible, however, then I would need RTTI in order to implement it. Because I need to check what type of class I am really holding at the moment.
