### ISSUE TITLE
deregistration

### ISSUE THREAD

**Issue by NuckNuck** [rttrorg/rttr#79]
Hi,
i have a application which loads multiple dynamic libraryies, with dlopen. The automatic registration works find so fare. If i close the dynamic loaded library with dlclose, the registered type infos are still registered. During the application shutdown a segfault occurs in the type_database destruction process.

Here a segfault callstack. **wo::ebs::TBlueprint** is a type from a library which was unloaded with dlclose. Is it possible to deregister the type infos before unloading a library?

Thanks,
Bastian

`--  0 ??()

--  1 rttr::detail::method_wrapper<void (**wo::ebs::TBlueprint**::*)(std::shared_ptr<wo::ebs::cmp::IComponent> const&), (rttr::access_levels)0, rttr::detail::default_invoke, rttr::detail::default_args<>, rttr::detail::parameter_infos<rttr::detail::parameter_info_wrapper<std::shared_ptr<wo::ebs::cmp::IComponent> const&, 0ul, rttr::detail::no_param_name, void> >, 0ul>::**~method_wrapper()**() 

--  2 std::default_delete<rttr::detail::method_wrapper_base>::operator()() 

--  3 std::unique_ptr<rttr::detail::method_wrapper_base, std::default_delete<rttr::detail::method_wrapper_base> >::~unique_ptr() 

--  4 rttr::detail::type_database::class_member<rttr::detail::method_wrapper_base>::~class_member() 

--  5 std::_Destroy<rttr::detail::type_database::class_member<rttr::detail::method_wrapper_base> >() 

--  6 std::_Destroy_aux<false>::__destroy<rttr::detail::type_database::class_member<rttr::detail::method_wrapper_base>*>() 

--  7 std::_Destroy<rttr::detail::type_database::class_member<rttr::detail::method_wrapper_base>*>() 

--  8 std::_Destroy<rttr::detail::type_database::class_member<rttr::detail::method_wrapper_base>*, rttr::detail::type_database::class_member<rttr::detail::method_wrapper_base> >() 

--  9 std::vector<rttr::detail::type_database::class_member<rttr::detail::method_wrapper_base>, std::allocator<rttr::detail::type_database::class_member<rttr::detail::method_wrapper_base> > >::~vector() 

-- 10 rttr::detail::type_database::~type_database() 

-- 11 __cxa_finalize() 

-- 12 __do_global_dtors_aux() 

-- 13 ??() 

-- 14 _dl_close_worker() 
`

**Comment by MrMilad** [comment]
i have same issue.

**Comment by acki-m** [comment]
I will take a look.

**Comment by NuckNuck** [comment]
I could identifiy some steps to fix this:

1.  rttr::detail::type_database needs deregistration functions for every kind of registered info.
```c++
...
void register_method(const type& t, std::unique_ptr<method_wrapper_base> meth);
void deregister_method(const type& t, std::unique_ptr<method_wrapper_base> meth);
...
```
This is the easiest approach because the registration process with **RTTR_REGISTRATION** knows all registered infos.

2. the registration process needs a lifetime scope.
 Currently the **RTTR_REGISTRATION** macro implements a struct (_rttr__auto__register___), wich calls _rttr_auto_register_reflection_function__. The _rttr__auto__register___ struct is the right place to register (constructor) and deregister (destructor) the type infos. To achieve this the _rttr__auto__register___ struct could hold the generated _registration::bind_ objects. The _rttr__auto__register___ constructor could  trigger the registration an the destructor the deregistration. So, the **RTTR_REGISTRATION** could be changed to create an object with a lifetime scope.
```c++
struct rttr__auto__register__
{
    rttr__auto__register__()
    {
        // registration
    }
    ~rttr__auto__register__()
    {
        // deregistration
    }
};
namespace
{
    const rttr__auto__register__ typeRegistrationObject;
}
```

I like your library and I hope my suggestions can help to provide this feature.

Bastian

**Comment by acki-m** [comment]
I found a better solution, without the static variable in the auto register macro. Can you check it out, whether it works for you now?

**Comment by NuckNuck** [comment]
Great!

Now it's possible to load ANd unload libraries wich contain rttr type registrations.
Thank you!

**Comment by acki-m** [comment]
@NuckNuck 
You need my newest changes of PR: #113 , otherwise you might get an access violation when loading the library again.

**Comment by NuckNuck** [comment]
Thank you!
I have updated.
