### ISSUE TITLE
Clarification / sample app for OSX

### ISSUE THREAD

**Issue by johndpope** [rttrorg/rttr#8]
So I successfully built an xcode project using
  cmake -G Xcode 

I can see the rttr dylib target / is this for injecting into existing processes? 

My steps so far 

I create a new target > Terminal App inside the xcode project 
I include the rttr_core framework add the rttr as a dependency and run

#include <rttr/registration> // < this line fails. 
using namespace rttr;

Normally to resolve this / I'd check to see if the headers are included in the 'framework' - but 
it doesn't appear that the rttr is a framwork with public headers / or there's no headers. or I am I missing something. 

![screen shot 2016-01-25 at 1 03 16 pm](https://cloud.githubusercontent.com/assets/289994/12540956/1066bb46-c364-11e5-8ad6-18329bfd2226.png)

My bigger task is this > https://reverseengineering.stackexchange.com/questions/11840/recycling-private-framework-sdk-no-header-files-osx

I can point to 
#include "registration_impl.h"
using namespace rttr;
// but this runs into lots of errors. 

the registration file appears all commented out 

![screen shot 2016-01-25 at 1 31 08 pm](https://cloud.githubusercontent.com/assets/289994/12541220/fcf312e0-c367-11e5-8378-d1c794792d12.png)

Have you considered using virtual box osx simulator?
 If anyone gets this working on OSX I'd appreciate any help on steps taken to get  up and running.

**Comment by acki-m** [comment]
I have no mac hardware to run osx myself. However, via travis-ci I was successfully able to compile and run RTTR on OSX. See yourself: https://travis-ci.org/rttrorg/rttr/jobs/103709101

Did you followed the install guide? http://www.rttr.org/doc/rttr-0-9-5/building_install_page.html
When you have installed RTTR, you should point with a environment variable to the install dir:
`set RTTR_DIR=c:/rttr-1.0.0-win64-vs2013`

I know @mgee runs OSX, maybe he can help you.

PS: You should not include any impl headers.

**Comment by johndpope** [comment]
I didn't set the RTTR_DIR / that looks very specific to windows. 
I guess I must be missing the use case of this app  -  I had imagine it being something similar to dot net reflector but in fact it depends on the code being including pre-compilation?

I found an example of dylib injection for an app.  https://github.com/nqn/dylib
Is this related to this code? Could RTTR just hook into a process and introspect away (without necessarily having access to source code). Is the RTTR capable of this? 

Or said another way - could I build a project and have it introspect an included third party library?

**Comment by mgee** [comment]
The error indicates that you have not set up the correct include path for RTTR. To further track down the error it would be helpful if you could post the command line used to compile the `main.cpp` from the screenshot.

**Comment by acki-m** [comment]
`RTTR_DIR` is not specific to windows, it is needed for CMake to find the CMake find modules of RTTR.

RTTR cannot hook into an external process and retrieve the reflection information.
You need at least access to the class declaration of the third party lib and then manually register the members you want to reflect.

A typical use case would be following:
You create a plugin (which would be in your case the 3rdParty lib), where you register your reflection information within `RTTR_REGISTRATION`.
Then you can load the plugin and retrieve the reflection information of your particular type via `rttr::type::get_by_name()`.
Therefore you don't need access to the header files, you can create, invoke and set properties of classes, without the actual type.

I think, what you are looking for is a hooking library, but without exported symbols I think it will be difficult.

**Comment by johndpope** [comment]
thanks for coming back so quickly. I think this maybe more suited -> https://github.com/kpwn/harpoon
thanks again. P.S. unlike windows apps / I read somewhere that OSX apps include their symbols by default.
