### ISSUE TITLE
Access derived type from base class (inside the instance)?

### ISSUE THREAD

**Issue by fjgonzalez** [rttrorg/rttr#82]
Hi,

Pseudo-code:

class Foo
{
  Foo()
  {
   // Get type of "boo" instance
  }
}

class Boo : Foo
{
 Boo() : Foo() {}
}

// Here I register metadata to Boo but i want to access theirs from method of its base class.

Is it possible?

Regards,

**Comment by acki-m** [comment]
I don't really understand what you trying to achieve. Please rephrase your question.

**Comment by fjgonzalez** [comment]
Sorry, my answer was very poor.

I have two classes (father and son). In my case, I add metadata with RTTR into the child class but i need to access at this metadata from the base class. I want to know if it is possible access to rttr:type of the child from the base class. Because with the type of base class i can not access to the child metadata. 

class Father
{
public:
void Read()
{
 // Here i need to access at Son metadata but i have not save in any momet the specific type of Son.
}
}

class Son : public Father
{
}

// Add code to add metada into Son class

**Comment by acki-m** [comment]
Try something like this:
```
rttr::type::get(*this).get_metadata(...);
```

**Comment by fjgonzalez** [comment]
It does not work for me:.

Method in the base class:

{
   rttr::type typeOfInstance = rttr::type::get(*this);
    rttr::variant variantFactoryName = typeOfInstance.get_metadata(NetMessage::Metadata::Factory);
    if (variantFactoryName.is_valid())
    {
        mFactoryName = variantFactoryName.get_value<std::string>(); // <-- NO ENTER HERE
    }
}

In the cpp of the child class:
rttr::registration::class_<Dummy>("Dummy")
(
        metadata(NetMessage::Metadata::Factory, std::string("Test")),
        metadata(NetMessage::Metadata::MessageId, 100)
    )
    .constructor<>()
    (
        policy::ctor::as_raw_ptr
    );

**Comment by fjgonzalez** [comment]
Sample code:

`class Foo
{
    RTTR_ENABLE()

public:

    Foo()
    {
        rttr::type typeOfInstance = rttr::type::get(*this);

        rttr::variant variantMetada = typeOfInstance.get_metadata(100);

        int value = 0;
        if (variantMetada.is_valid())
        {
            value = variantMetada.get_value<int>();
        }
    }
};

class Boo : public Foo
{
    RTTR_ENABLE(Foo)
};

RTTR_REGISTRATION
{
    using namespace rttr;

    rttr::registration::class_<Foo>("Foo")
    .constructor<>()
    (
        policy::ctor::as_raw_ptr
    );

    rttr::registration::class_<Boo>("Boo")
    (
        metadata(100, 200)
    )
    .constructor<>()
    (
        policy::ctor::as_raw_ptr
    );
}`

**Comment by acki-m** [comment]
Your problem is pretty simple:
The object is not completely created in the base ctor.
First the base ctor will be called, then the parent one and so on.

So in order to fix it, make a new member function and call this, after Boo was created.
```
void init()
{
    rttr::type typeOfInstance = rttr::type::get(*this);

    rttr::variant variantMetada = typeOfInstance.get_metadata(100);

    int value = 0;
    if (variantMetada.is_valid())
    {
        value = variantMetada.get_value<int>();
    }
}
```

```
Boo obj;
obj.init();
```
