### ISSUE TITLE
Limits for numeric properties

### ISSUE THREAD

**Issue by pgrohs** [rttrorg/rttr#92]
I appreciate your library a lot. But I wonder if there is the possibility to add numeric limits to registered properties? Using metadata does not appear the optimal way as this does not check the property values with respect to the limits.

**Comment by acki-m** [comment]
I don't know whether it is practical to add some pre condition before invoke.
But it would be possible to invoke some lambda or function before the registered accessor.
```
rttr::registration::class<foo>("foo")
                          .property("my_prop", &foo::value)
                                   ( 
                                       check_invoke([](int v){ return (v > 0 && v < 100}; 
                                   );
```
Something like this, however I don't know how useful this is. Maybe this should be better done in the client class itself.
