### ISSUE TITLE
Register new RTTR types via Plugins?

### ISSUE THREAD

**Issue by hydexon** [rttrorg/rttr#94]
I saw in the README.md which the RTTR library claims to support the registration of new types dynamically like plugins, and also i saw some issues which involves shared libraries loaded dynamically without needing to link the plugin's header files and such.

But i can't find information about them of how to do it, RTTR automatically register the new types statically when a dynamic library o static library is loaded dynamically without calling a special function which register them dynamically?

**Comment by volcoma** [comment]
yeah that would be a game changing feature.

**Comment by hydexon** [comment]
I've tested it myself, in Windows just load the DLL before doing any RTTR call, and the DLL declared RTTR types will be available in the host application. I don't know about Linux and Mac.

**Comment by volcoma** [comment]
what about load/unload then load a different one after many rttr calls

**Comment by acki-m** [comment]
The loading of RTTR data should work.
However, the automatic unloading of registration information is not implemented right now.
But I am working on it.

**Comment by hydexon** [comment]
> what about load/unload then load a different one after many rttr calls
That would nice for kind of Hot-reload reflected data types, recompile your DLL without recompiling the host, as long have the same RTTR library binary version.

**Comment by acki-m** [comment]
Fixed via PR: #116
